gui:
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: "arrowAndNumber"
  switchTabsWithPanelJumpKeys: true
  enlargedSideViewLocation: top
  sidePanelWidth: 0.2
  # Dracula Pro Alucard Theme
  theme:
    activeBorderColor:
      - "#644AC9"  # purple
      - bold
    inactiveBorderColor:
      - "#635D97"  # comment
    optionsTextColor:
      - "#036A96"  # cyan
    selectedLineBgColor:
      - "#CFCFDE"  # selection
    selectedRangeBgColor:
      - "#CFCFDE"  # selection
    cherryPickedCommitBgColor:
      - "#E6E6E6"  # subtle background
    cherryPickedCommitFgColor:
      - "#644AC9"  # purple
    unstagedChangesColor:
      - "#CB3A2A"  # red
    defaultFgColor:
      - "#1F1F1F"  # foreground
    searchingActiveBorderColor:
      - "#846E15"  # yellow
      - bold
git:
  pagers:
    - pager: delta --paging=never --features=alucard
      colorArg: always
