gui:
  nerdFontsVersion: "3"
  showDivergenceFromBaseBranch: "arrowAndNumber"
  switchTabsWithPanelJumpKeys: true
  enlargedSideViewLocation: top
  sidePanelWidth: 0.2
  # Tokyo Night Dark (night variant)
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#27a1b9"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    selectedRangeBgColor:
      - "#283457"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
    searchingActiveBorderColor:
      - "#ff9e64"
      - bold
git:
  pagers:
    - pager: delta --paging=never --features=tokyonight-night
      colorArg: always
