cask_args appdir: "/Applications"

# CLI — macOS-only holdouts; cross-platform CLI tools live in mise
# (~/.config/mise/config.toml)
brew "coreutils"
brew "git"
brew "libpq"
brew "redis"
brew "tmux"
brew "tree"

# PHP build deps — mise's php plugin (vfox-php) compiles from source
brew "autoconf"
brew "bison"
brew "bzip2"
brew "curl"
brew "libedit"
brew "libiconv"
brew "freetype"
brew "gmp"
brew "icu4c"
brew "jpeg-turbo"
brew "libpng"
brew "libsodium"
brew "libxml2"
brew "libzip"
brew "oniguruma"
brew "openssl@3"
brew "pkg-config"
brew "re2c"
brew "readline"
brew "webp"
brew "zlib"

# UI
cask "1password-cli"
cask "alt-tab"
cask "ghostty"
cask "imageoptim"
cask "thaw"
