cask_args appdir: "/Applications"
tap "heroku/brew"
tap "puma/puma"


brew "bat"
brew "fzf"
brew "tree"
brew "wget"

brew "gh"
brew "git"
brew "git-delta"
brew "heroku"
brew "starship"
brew "mise"
brew "redis"
brew "neovim"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "libpq"
brew "overmind"
brew "puma-dev"
brew "lazygit"
brew "gh"
brew "atuin"
brew "puma-dev"
cask "font-monaspace-nerd-font"
cask "font-hack-nerd-font"
brew "libyaml" # For Ruby 3.x

cask "jordanbaird-ice"
cask "postgres-unofficial"
cask "alt-tab"
cask "ghostty"
cask "cursor"
cask "google-chrome"
cask "helium-browser"

brew "chezmoi"
brew "uv"
