cask_args appdir: "/Applications"
tap "heroku/brew"
tap "puma/puma"


brew "bat"
brew "fzf"
brew "tree"
brew "wget"

brew "gh"
brew "git"
brew "git-delta"
brew "heroku"
brew "mise"
brew "redis"
brew "neovim"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "libpq"
brew "overmind"
brew "lazygit"
brew "gh"
brew "atuin"
cask "font-hack-nerd-font"
brew "libyaml" # For Ruby 3.x
brew "trash"
brew  "steipete/tap/summarize"

cask "jordanbaird-ice"
cask "postgres-unofficial"
cask "alt-tab"
cask "ghostty"

brew "chezmoi"
brew "uv"
brew "yazi"
brew "sevenzip"
brew "jq"
brew "poppler"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "zoxide"
brew "resvg"
cask "font-symbols-only-nerd-font"
cask "1password"
cask "raycast"

